import {
  User,
  AdminUser,
  RolePermission,
  OtpVerificationLog,
  ActiveSession,
  HostData,
  EventCategory,
  EventProduct,
  FlashSale,
  EventGuest,
  EventRegistration,
  EventAttendance,
  PackageInvoice,
  PaymentSessionLog,
  GiftInvoiceRecord,
  SupportTicket,
  TicketInteraction,
  ThemeReview,
  PromoPopup,
  SocialMediaAccount,
  FaqCategory,
  FaqItem,
  ContactMessage,
  NotificationLog,
  DeadNotification,
  SiteSettings,
  TransactionSettings,
  GatewaySettings,
  ActivityLog,
} from "@/types/superadmin";

// ─── Modul 2: Users & Admins ────────────────────────────────────────────────
export const MOCK_USERS: User[] = [
  {
    id: 101,
    name: "Rizky Firmansyah",
    email: "rizky.manda@wedding.com",
    phone: "081234567890",
    address: "Jl. Senopati No. 42, Kebayoran Baru, Jakarta Selatan",
    role: "host",
    status: "active",
    isVerified: true,
    createdAt: "2026-07-15T10:30:00Z",
    totalOrders: 2,
    hostBalance: 2450000,
  },
  {
    id: 102,
    name: "Nabila Putri Maharani",
    email: "nabila.putri@gmail.com",
    phone: "081987654321",
    address: "Komplek Dago Asri B-12, Bandung, Jawa Barat",
    role: "host",
    status: "active",
    isVerified: true,
    createdAt: "2026-08-01T14:15:00Z",
    totalOrders: 1,
    hostBalance: 1750000,
  },
  {
    id: 103,
    name: "Budi Santoso",
    email: "budi.santoso@yahoo.com",
    phone: "082155556666",
    address: "Jl. Kaliurang KM 5, Sleman, DI Yogyakarta",
    role: "host",
    status: "active",
    isVerified: true,
    createdAt: "2026-08-10T09:00:00Z",
    totalOrders: 1,
    hostBalance: 5200000,
  },
  {
    id: 104,
    name: "Agus Pratama",
    email: "agus.pratama99@spam.org",
    phone: "085712348899",
    address: "Surabaya",
    role: "guest_registered",
    status: "banned",
    isVerified: false,
    createdAt: "2026-08-20T11:45:00Z",
    totalOrders: 0,
    hostBalance: 0,
  },
  {
    id: 105,
    name: "Siti Rahmawati",
    email: "siti.rahma@outlook.com",
    phone: "081399887766",
    address: "Semarang, Jawa Tengah",
    role: "guest_registered",
    status: "active",
    isVerified: true,
    createdAt: "2026-08-25T16:20:00Z",
    totalOrders: 0,
    hostBalance: 0,
  },
];

export const MOCK_ADMINS: AdminUser[] = [
  {
    id: 1,
    name: "Adji Bhawanto (Lead)",
    email: "superadmin@momeninvite.com",
    phone: "081122334455",
    address: "Jakarta HQ",
    role: "superadmin",
    status: "active",
    failedAttempts: 0,
    lockedUntil: null,
    lastLoginAt: "2026-09-08T07:15:00Z",
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: 2,
    name: "Dina Operasional",
    email: "dina.ops@momeninvite.com",
    phone: "081299443322",
    address: "Jakarta Ops Floor",
    role: "admin",
    status: "active",
    failedAttempts: 0,
    lockedUntil: null,
    lastLoginAt: "2026-09-08T06:40:00Z",
    createdAt: "2026-03-15T09:00:00Z",
  },
  {
    id: 3,
    name: "Fajar Support Staff",
    email: "fajar.help@momeninvite.com",
    phone: "087811223344",
    address: "Bandung Remote Support",
    role: "admin",
    status: "inactive",
    failedAttempts: 3,
    lockedUntil: "2026-09-08T18:00:00Z",
    lastLoginAt: "2026-09-05T12:00:00Z",
    createdAt: "2026-05-10T10:00:00Z",
  },
];

export const MOCK_ROLES: RolePermission[] = [
  {
    id: 1,
    name: "superadmin",
    description: "Akses Penuh Tanpa Batas: Persetujuan Penarikan Saldo, Konfigurasi Gateway, Manajemen Admin & Audit Trail",
    permissions: ["ALL_ACCESS", "WITHDRAWAL_APPROVAL", "ADMIN_MANAGEMENT", "SYSTEM_CONFIG", "AUDIT_LOG_VIEW"],
    userCount: 1,
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: 2,
    name: "admin",
    description: "Staf Operasional: Verifikasi Pesanan, Moderasi Konten & Review, Penanganan Tiket Bantuan, Log Notifikasi",
    permissions: ["ORDER_VERIFY", "CONTENT_MODERATE", "TICKET_MANAGE", "NOTIF_VIEW", "REVIEW_MODERATE"],
    userCount: 2,
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: 3,
    name: "host",
    description: "Penyelenggara Acara: Membuat Undangan, Mengatur Buku Tamu, Menerima Amplop Digital & Menarik Saldo",
    permissions: ["CREATE_EVENT", "MANAGE_GUESTS", "RECEIVE_GIFTS", "REQUEST_WITHDRAW"],
    userCount: 3,
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: 4,
    name: "guest_registered",
    description: "Tamu Terdaftar: Mengisi RSVP, Mengirim Amplop Kado Digital, Mengakses Tiket Acara Publik",
    permissions: ["SUBMIT_RSVP", "SEND_GIFT", "ACCESS_TICKET"],
    userCount: 2,
    createdAt: "2026-01-01T00:00:00Z",
  },
];

export const MOCK_OTP_LOGS: OtpVerificationLog[] = [
  {
    id: 1,
    target: "081234567890",
    channel: "whatsapp",
    purpose: "register",
    isExpired: true,
    usedAt: "2026-09-08T06:12:00Z",
    createdAt: "2026-09-08T06:10:00Z",
  },
  {
    id: 2,
    target: "rizky.manda@wedding.com",
    channel: "email",
    purpose: "reset_password",
    isExpired: true,
    usedAt: "2026-09-07T14:30:00Z",
    createdAt: "2026-09-07T14:25:00Z",
  },
  {
    id: 3,
    target: "081987654321",
    channel: "whatsapp",
    purpose: "login_2fa",
    isExpired: true,
    usedAt: "2026-09-08T07:05:00Z",
    createdAt: "2026-09-08T07:02:00Z",
  },
];

export const MOCK_ACTIVE_SESSIONS: ActiveSession[] = [
  {
    sid: "sess_pg_98a72b11",
    userId: 1,
    userName: "Adji Bhawanto",
    role: "superadmin",
    ipAddress: "182.1.24.110",
    deviceInfo: "Chrome 128 (Windows 11)",
    expiresAt: "2026-09-09T07:15:00Z",
    createdAt: "2026-09-08T07:15:00Z",
  },
  {
    sid: "sess_pg_34c56e99",
    userId: 2,
    userName: "Dina Operasional",
    role: "admin",
    ipAddress: "103.20.14.5",
    deviceInfo: "Safari 17 (macOS Sonoma)",
    expiresAt: "2026-09-09T06:40:00Z",
    createdAt: "2026-09-08T06:40:00Z",
  },
];

// ─── Modul 3: Hosts Penyelenggara ──────────────────────────────────────────
export const MOCK_HOSTS: HostData[] = [
  {
    id: 12,
    userId: 101,
    name: "Rizky Firmansyah",
    email: "rizky.manda@wedding.com",
    phone: "081234567890",
    balance: 2450000,
    allowNotifWa: true,
    createdAt: "2026-07-15T10:30:00Z",
    totalEvents: 2,
    totalGiftsReceived: 7450000,
    totalWithdrawn: 5000000,
    pendingWithdrawalCount: 0,
  },
  {
    id: 13,
    userId: 102,
    name: "Nabila Putri Maharani",
    email: "nabila.putri@gmail.com",
    phone: "081987654321",
    balance: 1750000,
    allowNotifWa: true,
    createdAt: "2026-08-01T14:15:00Z",
    totalEvents: 1,
    totalGiftsReceived: 4250000,
    totalWithdrawn: 2500000,
    pendingWithdrawalCount: 1,
  },
  {
    id: 14,
    userId: 103,
    name: "Budi Santoso",
    email: "budi.santoso@yahoo.com",
    phone: "082155556666",
    balance: 5200000,
    allowNotifWa: false,
    createdAt: "2026-08-10T09:00:00Z",
    totalEvents: 1,
    totalGiftsReceived: 5200000,
    totalWithdrawn: 0,
    pendingWithdrawalCount: 0,
  },
];

// ─── Modul 4: Kategori & Katalog ───────────────────────────────────────────
export const MOCK_CATEGORIES: EventCategory[] = [
  {
    id: 1,
    name: "Pernikahan (Wedding)",
    slug: "wedding",
    requiresRsvp: true,
    isActive: true,
    productCount: 12,
    description: "Template undangan akad, resepsi, countdown, amplop kado & buku tamu pernikahan.",
    createdAt: "2026-01-10T00:00:00Z",
  },
  {
    id: 2,
    name: "Ulang Tahun (Birthday)",
    slug: "birthday",
    requiresRsvp: true,
    isActive: true,
    productCount: 8,
    description: "Undangan ultah anak, sweet seventeen, hingga dewasa dengan tema ceria.",
    createdAt: "2026-01-15T00:00:00Z",
  },
  {
    id: 3,
    name: "Ucapan Interaktif (Birthday Greeting)",
    slug: "birthday_greeting",
    requiresRsvp: false,
    isActive: true,
    productCount: 6,
    description: "Kartu ucapan digital emosional, surat amplop, dan kartu harapan personal.",
    createdAt: "2026-02-01T00:00:00Z",
  },
  {
    id: 4,
    name: "Gathering & Seminar Publik",
    slug: "gathering",
    requiresRsvp: true,
    isActive: true,
    productCount: 4,
    description: "Acara komunitas, tiket seminar berbayar, dan konfirmasi presensi scan QR.",
    createdAt: "2026-03-01T00:00:00Z",
  },
];

export const MOCK_PRODUCTS: EventProduct[] = [
  {
    id: 1,
    eventCategoryId: 1,
    categoryName: "Pernikahan (Wedding)",
    name: "Elegance Royal Gold",
    slug: "elegance-royal-gold",
    description: "Desain mewah aksen emas kerajaan dengan efek partikel dan amplop interaktif.",
    badge: "Best Seller",
    themeSlug: "wedding-royal-gold",
    price: 149000,
    thumbnailUrl: "https://images.unsplash.com/photo-1519741497674-611481863552?w=500&auto=format&fit=crop&q=60",
    isPublished: true,
    totalSold: 428,
    createdAt: "2026-02-10T00:00:00Z",
  },
  {
    id: 2,
    eventCategoryId: 1,
    categoryName: "Pernikahan (Wedding)",
    name: "Minimalist Botanical Sage",
    slug: "minimalist-botanical-sage",
    description: "Tema bernuansa hijau sage natural, minimalis, dan elegan dengan animasi daun.",
    badge: "Popular",
    themeSlug: "wedding-sage-green",
    price: 129000,
    thumbnailUrl: "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=500&auto=format&fit=crop&q=60",
    isPublished: true,
    totalSold: 312,
    createdAt: "2026-03-05T00:00:00Z",
  },
  {
    id: 3,
    eventCategoryId: 2,
    categoryName: "Ulang Tahun (Birthday)",
    name: "Pastel Playful Kids",
    slug: "pastel-playful-kids",
    description: "Warna pastel ceria dengan karakter animasi ramah anak dan musik riang.",
    badge: "New",
    themeSlug: "birthday-pastel-kids",
    price: 99000,
    thumbnailUrl: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=500&auto=format&fit=crop&q=60",
    isPublished: true,
    totalSold: 184,
    createdAt: "2026-04-01T00:00:00Z",
  },
  {
    id: 4,
    eventCategoryId: 3,
    categoryName: "Ucapan Interaktif",
    name: "Warm Memory Envelope Letter",
    slug: "warm-memory-letter",
    description: "Surat digital buka amplop romantis dengan linimasa kenangan foto berharga.",
    badge: "Trending",
    themeSlug: "greeting-envelope-letter",
    price: 79000,
    thumbnailUrl: "https://images.unsplash.com/photo-1513151233558-d860c5398176?w=500&auto=format&fit=crop&q=60",
    isPublished: true,
    totalSold: 96,
    createdAt: "2026-05-15T00:00:00Z",
  },
];

export const MOCK_FLASH_SALES: FlashSale[] = [
  {
    id: 1,
    eventProductId: 1,
    productName: "Elegance Royal Gold",
    normalPrice: 149000,
    promoPrice: 89000,
    label: "Promo Gajian Diskon 40%",
    startsAt: "2026-09-01T00:00:00Z",
    endsAt: "2026-09-10T23:59:59Z",
    status: "active",
  },
  {
    id: 2,
    eventProductId: 3,
    productName: "Pastel Playful Kids",
    normalPrice: 99000,
    promoPrice: 59000,
    label: "Flash Sale Weekend",
    startsAt: "2026-09-12T00:00:00Z",
    endsAt: "2026-09-14T23:59:59Z",
    status: "scheduled",
  },
];

// ─── Modul 6: Tamu & Presensi ───────────────────────────────────────────────
export const MOCK_GUESTS: EventGuest[] = [
  {
    id: 1,
    eventOrderId: 501,
    eventTitle: "The Wedding of Rizky & Amanda",
    guestCode: "VIP-001",
    name: "Prof. Dr. Ir. Hendro Wijaya",
    phone: "081233445566",
    email: "hendro.w@univ.ac.id",
    category: "VIP",
    groupSession: "Sesi 1 (Akad & Resepsi Siang)",
    tableNumber: "Meja VIP 1",
    maxGuests: 2,
    rsvpStatus: "attending",
    rsvpPax: 2,
    rsvpWishes: "Selamat menempuh hidup baru Amanda & Rizky, semoga sakinah mawaddah warahmah.",
    invitationOpenedAt: "2026-09-07T14:30:00Z",
    createdAt: "2026-08-28T10:00:00Z",
  },
  {
    id: 2,
    eventOrderId: 501,
    eventTitle: "The Wedding of Rizky & Amanda",
    guestCode: "KLG-012",
    name: "Om Dani & Keluarga",
    phone: "081877665544",
    category: "Keluarga",
    groupSession: "Sesi 1 (Akad & Resepsi Siang)",
    tableNumber: "Meja Fam B",
    maxGuests: 4,
    rsvpStatus: "attending",
    rsvpPax: 4,
    rsvpWishes: "Barakallah, langgeng sampai kakek nenek!",
    invitationOpenedAt: "2026-09-06T19:00:00Z",
    createdAt: "2026-08-28T10:05:00Z",
  },
  {
    id: 3,
    eventOrderId: 501,
    eventTitle: "The Wedding of Rizky & Amanda",
    guestCode: "TMN-089",
    name: "Bagas Wicaksono",
    phone: "085611223399",
    email: "bagas.w@startup.id",
    category: "Teman",
    groupSession: "Sesi 2 (Resepsi Malam)",
    tableNumber: "Meja F-4",
    maxGuests: 1,
    rsvpStatus: "declined",
    rsvpPax: 0,
    rsvpWishes: "Maaf banget belum bisa hadir karena dinas ke luar pulau bro.",
    invitationOpenedAt: "2026-09-07T08:15:00Z",
    createdAt: "2026-08-28T10:10:00Z",
  },
  {
    id: 4,
    eventOrderId: 502,
    eventTitle: "1st Birthday Little Arka",
    guestCode: "KID-005",
    name: "Tante Maya & Kenzo",
    phone: "081299881122",
    category: "Keluarga",
    maxGuests: 2,
    rsvpStatus: "pending",
    rsvpPax: 0,
    invitationOpenedAt: null,
    createdAt: "2026-08-29T11:00:00Z",
  },
];

export const MOCK_REGISTRATIONS: EventRegistration[] = [
  {
    id: 1,
    eventOrderId: 503,
    eventTitle: "Seminar Edukasi Finansial Keluarga 2026",
    userId: 101,
    userName: "Rizky Firmansyah",
    userEmail: "rizky.manda@wedding.com",
    ticketCode: "TCK-SEM-9901",
    ticketType: "VIP Early Bird",
    status: "confirmed",
    paxCount: 1,
    registeredAt: "2026-09-01T15:00:00Z",
  },
  {
    id: 2,
    eventOrderId: 503,
    eventTitle: "Seminar Edukasi Finansial Keluarga 2026",
    userId: 105,
    userName: "Siti Rahmawati",
    userEmail: "siti.rahma@outlook.com",
    ticketCode: "TCK-SEM-9902",
    ticketType: "Regular Pass",
    status: "confirmed",
    paxCount: 2,
    registeredAt: "2026-09-02T10:30:00Z",
  },
];

export const MOCK_ATTENDANCES: EventAttendance[] = [
  {
    id: 1,
    eventOrderId: 501,
    eventTitle: "The Wedding of Rizky & Amanda",
    attendeeName: "Prof. Dr. Ir. Hendro Wijaya",
    attendeeType: "guest",
    qrCodeScanned: "VIP-001",
    actualPax: 2,
    sessionName: "Sesi 1 (Akad & Siang)",
    checkinMethod: "Scan QR",
    checkedInByLabel: "Dina (Meja VIP)",
    souvenirStatus: "Sudah Diberikan",
    gateOrDesk: "Pintu Selatan Lt 1",
    checkedInAt: "2026-09-08T03:45:00Z",
  },
  {
    id: 2,
    eventOrderId: 501,
    eventTitle: "The Wedding of Rizky & Amanda",
    attendeeName: "Om Dani & Keluarga",
    attendeeType: "guest",
    qrCodeScanned: "KLG-012",
    actualPax: 4,
    sessionName: "Sesi 1 (Akad & Siang)",
    checkinMethod: "Scan QR",
    checkedInByLabel: "Dina (Meja VIP)",
    souvenirStatus: "Sudah Diberikan",
    gateOrDesk: "Pintu Utama",
    checkedInAt: "2026-09-08T04:10:00Z",
  },
];

// ─── Modul 7: Keuangan & Billing ────────────────────────────────────────────
export const MOCK_INVOICES: PackageInvoice[] = [
  {
    id: 201,
    eventOrderId: 501,
    invoiceNumber: "INV-20260827-001",
    hostName: "Rizky Firmansyah",
    hostEmail: "rizky.manda@wedding.com",
    eventProductNameSnapshot: "Elegance Royal Gold",
    subtotal: 149000,
    tax: 0,
    total: 149000,
    dueDate: "2026-08-28T08:00:00Z",
    status: "SUCCESS",
    paidAt: "2026-08-27T08:25:00Z",
    paymentMethod: "DUITKU_QRIS",
    createdAt: "2026-08-27T08:00:00Z",
  },
  {
    id: 202,
    eventOrderId: 502,
    invoiceNumber: "INV-20260828-002",
    hostName: "Bunda Sarah",
    hostEmail: "sarah.bunda@gmail.com",
    eventProductNameSnapshot: "Pastel Playful Kids",
    subtotal: 99000,
    tax: 0,
    total: 99000,
    dueDate: "2026-08-29T09:00:00Z",
    status: "SUCCESS",
    paidAt: "2026-08-28T09:40:00Z",
    paymentMethod: "VA_BCA",
    createdAt: "2026-08-28T09:00:00Z",
  },
  {
    id: 203,
    eventOrderId: 503,
    invoiceNumber: "INV-20260901-003",
    hostName: "Budi Santoso",
    hostEmail: "budi.santoso@yahoo.com",
    eventProductNameSnapshot: "Warm Memory Envelope Letter",
    subtotal: 79000,
    tax: 0,
    total: 79000,
    dueDate: "2026-09-02T14:00:00Z",
    status: "EXPIRED",
    paidAt: null,
    paymentMethod: "VA_MANDIRI",
    createdAt: "2026-09-01T14:00:00Z",
  },
];

export const MOCK_PAYMENTS: PaymentSessionLog[] = [
  {
    id: 1,
    paymentReference: "DUI-TRX-889102",
    targetType: "Invoice Tema",
    targetNumber: "INV-20260827-001",
    amount: 149000,
    paymentMethod: "QRIS",
    status: "paid",
    signatureValid: true,
    webhookReceivedAt: "2026-08-27T08:25:10Z",
    payloadSnapshot: {
      merchantCode: "D12345",
      reference: "DUI-TRX-889102",
      amount: "149000",
      resultCode: "00",
      statusMessage: "SUCCESS",
    },
    createdAt: "2026-08-27T08:00:00Z",
  },
  {
    id: 2,
    paymentReference: "DUI-TRX-889103",
    targetType: "Amplop Kado",
    targetNumber: "GIFT-20260908-011",
    amount: 500000,
    paymentMethod: "QRIS",
    status: "paid",
    signatureValid: true,
    webhookReceivedAt: "2026-09-08T07:30:05Z",
    payloadSnapshot: {
      merchantCode: "D12345",
      reference: "DUI-TRX-889103",
      amount: "500000",
      resultCode: "00",
      statusMessage: "SUCCESS",
    },
    createdAt: "2026-09-08T07:29:00Z",
  },
];

export const MOCK_GIFT_INVOICES: GiftInvoiceRecord[] = [
  {
    id: 1,
    hostId: 12,
    hostName: "Rizky Firmansyah",
    eventOrderId: 501,
    eventTitle: "The Wedding of Rizky & Amanda",
    senderName: "Andi Setiawan & Istri",
    senderMessage: "Selamat menempuh hidup baru bro Rizky & Manda!",
    amount: 500000,
    status: "paid",
    paymentMethod: "QRIS",
    paidAt: "2026-09-08T07:30:00Z",
    createdAt: "2026-09-08T07:29:00Z",
  },
  {
    id: 2,
    hostId: 12,
    hostName: "Rizky Firmansyah",
    eventOrderId: 501,
    eventTitle: "The Wedding of Rizky & Amanda",
    senderName: "Dian Sastrowardoyo",
    senderMessage: "Maaf ga bisa hadir fisik ya, sukses selalu acaranya!",
    amount: 1000000,
    status: "paid",
    paymentMethod: "VA BCA",
    paidAt: "2026-09-07T14:15:00Z",
    createdAt: "2026-09-07T14:10:00Z",
  },
  {
    id: 3,
    hostId: 13,
    hostName: "Nabila Putri Maharani",
    eventOrderId: 502,
    eventTitle: "1st Birthday Little Arka",
    senderName: "Om Bagus & Tante Rina",
    senderMessage: "Selamat ulang tahun Arka jagoan!",
    amount: 350000,
    status: "paid",
    paymentMethod: "GOPAY",
    paidAt: "2026-09-07T11:00:00Z",
    createdAt: "2026-09-07T10:55:00Z",
  },
];

// ─── Modul 8: Support Tickets & Reviews ─────────────────────────────────────
export const MOCK_TICKETS: SupportTicket[] = [
  {
    id: 301,
    hostId: 12,
    hostName: "Rizky Firmansyah",
    hostPhone: "081234567890",
    eventTitle: "The Wedding of Rizky & Amanda",
    issueType: "billing",
    title: "Saldo amplop digital belum otomatis masuk setelah tamu transfer QRIS",
    description: "Halo admin, ada tamu saya atas nama Reza yang barusan bayar QRIS 250rb tapi belum ada notifikasi masuk di dompet saya.",
    priority: "urgent",
    status: "open",
    assignedAdminId: null,
    assignedAdminName: "Belum Ditugaskan",
    createdAt: "2026-09-08T06:30:00Z",
    interactionsCount: 1,
  },
  {
    id: 302,
    hostId: 13,
    hostName: "Nabila Putri Maharani",
    hostPhone: "081987654321",
    eventTitle: "1st Birthday Little Arka",
    issueType: "design",
    title: "Request ganti font pada bagian judul surat undangan",
    description: "Bisa tolong ubah font judul hero agar lebih melengkung seperti tema vintage?",
    priority: "medium",
    status: "in_progress",
    assignedAdminId: 2,
    assignedAdminName: "Dina Operasional",
    createdAt: "2026-09-07T15:20:00Z",
    interactionsCount: 3,
  },
  {
    id: 303,
    hostId: 14,
    hostName: "Budi Santoso",
    hostPhone: "082155556666",
    issueType: "technical",
    title: "Tamu mengeluhkan musik latar tidak auto-play di iPhone",
    description: "Apakah ada pengaturan agar musik langsung bunyi saat web dibuka di browser Safari iOS?",
    priority: "low",
    status: "resolved",
    assignedAdminId: 2,
    assignedAdminName: "Dina Operasional",
    createdAt: "2026-09-05T09:00:00Z",
    resolvedAt: "2026-09-05T10:30:00Z",
    interactionsCount: 4,
  },
];

export const MOCK_TICKET_INTERACTIONS: Record<number, TicketInteraction[]> = {
  301: [
    {
      id: 1,
      ticketId: 301,
      senderType: "host",
      senderName: "Rizky Firmansyah",
      message: "Halo admin, ada tamu saya atas nama Reza yang barusan bayar QRIS 250rb tapi belum ada notifikasi masuk di dompet saya. Mohon bantuannya min.",
      createdAt: "2026-09-08T06:30:00Z",
    },
  ],
  302: [
    {
      id: 2,
      ticketId: 302,
      senderType: "host",
      senderName: "Nabila Putri Maharani",
      message: "Bisa tolong ubah font judul hero agar lebih melengkung seperti tema vintage?",
      createdAt: "2026-09-07T15:20:00Z",
    },
    {
      id: 3,
      ticketId: 302,
      senderType: "admin",
      senderName: "Dina Operasional",
      message: "Halo Kak Nabila! Tentu bisa, kami sedang sesuaikan CSS typography di template pesanan Kakak ya. Estimasi 15 menit lagi kami kabari kembali.",
      createdAt: "2026-09-07T15:35:00Z",
    },
  ],
};

export const MOCK_REVIEWS: ThemeReview[] = [
  {
    id: 1,
    userId: 101,
    userName: "Rizky Firmansyah",
    productName: "Elegance Royal Gold",
    categoryName: "Pernikahan",
    rating: 5,
    message: "Tampilannya mewah banget! Tamu-tamu undangan banyak yang memuji fitur amplop digital dan RSVP-nya yang sangat praktis.",
    isPublished: true,
    createdAt: "2026-09-01T10:00:00Z",
  },
  {
    id: 2,
    userId: 102,
    userName: "Nabila Putri",
    productName: "Pastel Playful Kids",
    categoryName: "Ulang Tahun",
    rating: 5,
    message: "Lucu dan responsif di HP! Animasi balon dan musiknya bikin anak-anak senang.",
    isPublished: true,
    createdAt: "2026-09-03T11:30:00Z",
  },
  {
    id: 3,
    userId: 104,
    userName: "Agus P.",
    productName: "Elegance Royal Gold",
    categoryName: "Pernikahan",
    rating: 2,
    message: "Agak lambat pas loading di koneksi 3G.",
    isPublished: false,
    createdAt: "2026-09-04T12:00:00Z",
  },
];

// ─── Modul 9: CMS & Marketing ───────────────────────────────────────────────
export const MOCK_POPUPS: PromoPopup[] = [
  {
    id: 1,
    title: "Promo Flash Sale Diskon 40% Tema Wedding",
    displayLocate: "landing",
    imgUrl: "https://images.unsplash.com/photo-1519741497674-611481863552?w=800&auto=format&fit=crop&q=60",
    linkBanner: "/catalog",
    startDate: "2026-09-01",
    endDate: "2026-09-15",
    isActive: true,
  },
  {
    id: 2,
    title: "Pengumuman Maintenance Server Malam Ini",
    displayLocate: "host",
    imgUrl: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&auto=format&fit=crop&q=60",
    linkBanner: "#",
    startDate: "2026-09-08",
    endDate: "2026-09-09",
    isActive: true,
  },
];

export const MOCK_SOSMED: SocialMediaAccount[] = [
  { id: 1, name: "Instagram", url: "https://instagram.com/momeninvite", icon: "photo_camera" },
  { id: 2, name: "TikTok", url: "https://tiktok.com/@momeninvite", icon: "smart_display" },
  { id: 3, name: "YouTube", url: "https://youtube.com/@momeninvite", icon: "play_circle" },
  { id: 4, name: "WhatsApp Business", url: "https://wa.me/6281122334455", icon: "chat" },
];

export const MOCK_FAQ_CATEGORIES: FaqCategory[] = [
  { id: 1, name: "Pemesanan & Pembayaran", queueNumber: 1, itemCount: 4 },
  { id: 2, name: "Fitur Buku Tamu & RSVP", queueNumber: 2, itemCount: 3 },
  { id: 3, name: "Amplop Kado Digital", queueNumber: 3, itemCount: 4 },
];

export const MOCK_FAQ_ITEMS: FaqItem[] = [
  {
    id: 1,
    faqCategoryId: 1,
    categoryName: "Pemesanan & Pembayaran",
    question: "Berapa lama masa aktif undangan web Momen Invite?",
    answer: "Undangan aktif selama 1 tahun penuh sejak tanggal pemesanan selesai, dan tetap dapat diakses untuk melihat kembali ucapan doa para tamu.",
    queueNumber: 1,
    isActive: true,
  },
  {
    id: 2,
    faqCategoryId: 3,
    categoryName: "Amplop Kado Digital",
    question: "Bagaimana cara mencairkan uang amplop digital ke rekening bank saya?",
    answer: "Host cukup membuka menu Keuangan di dashboard, masukkan nomor rekening tujuan, lalu geser slider konfirmasi untuk penarikan dana.",
    queueNumber: 1,
    isActive: true,
  },
];

export const MOCK_CONTACT_MESSAGES: ContactMessage[] = [
  {
    id: 1,
    name: "Dewi Lestari",
    email: "dewi.lestari@gmail.com",
    phone: "081288990011",
    subject: "Penawaran Kerjasama Wedding Organizer",
    message: "Halo tim Momen Invite, kami dari WO di Surabaya ingin mengajukan kemitraan paket bundling undangan digital untuk 50 klien kami tahun ini.",
    status: "unread",
    createdAt: "2026-09-08T05:30:00Z",
  },
  {
    id: 2,
    name: "Kurniawan",
    email: "kurnia@techcorp.id",
    phone: "085677889900",
    subject: "Pertanyaan Integrasi Tiket Seminar",
    message: "Apakah Momen Invite support registrasi tiket berbayar dengan kuota 500 peserta?",
    status: "read",
    createdAt: "2026-09-07T11:15:00Z",
  },
];

// ─── Modul 10: Notification Logs ────────────────────────────────────────────
export const MOCK_NOTIF_LOGS: NotificationLog[] = [
  {
    id: 1,
    channel: "whatsapp",
    recipient: "081234567890",
    eventTitle: "The Wedding of Rizky & Amanda",
    subjectOrPreview: "Halo Kak Rizky! Selamat, pembayaran paket tema Elegance Royal Gold sebesar Rp 149.000 telah kami terima.",
    status: "sent",
    retryCount: 0,
    createdAt: "2026-08-27T08:25:00Z",
    providerResponse: "status: true, msg: 'Message queued'",
  },
  {
    id: 2,
    channel: "email",
    recipient: "rizky.manda@wedding.com",
    eventTitle: "The Wedding of Rizky & Amanda",
    subjectOrPreview: "Invoice Lunas #INV-20260827-001 - Momen Invite",
    status: "sent",
    retryCount: 0,
    createdAt: "2026-08-27T08:25:05Z",
    providerResponse: "200 OK id: res_9921b8",
  },
  {
    id: 3,
    channel: "whatsapp",
    recipient: "089988776655",
    subjectOrPreview: "Kode OTP Pendaftaran Anda adalah: 489211",
    status: "failed",
    retryCount: 3,
    createdAt: "2026-09-08T07:10:00Z",
    providerResponse: "status: false, msg: 'Invalid phone number or device disconnected'",
  },
];

export const MOCK_DEAD_NOTIFICATIONS: DeadNotification[] = [
  {
    id: 1,
    channel: "whatsapp",
    recipient: "089988776655",
    payloadSummary: "Kode OTP Pendaftaran Akun",
    errorMessage: "Device disconnected / Timeout 30000ms after 3 retries",
    retryCount: 3,
    status: "dead",
    lastAttemptAt: "2026-09-08T07:15:00Z",
  },
];

// ─── Modul 11 & 12: Settings & Activity Logs ────────────────────────────────
export const MOCK_SITE_SETTINGS: SiteSettings = {
  websiteName: "Momen Invite",
  title: "Momen Invite - Platform Undangan Digital & Social-Fintech No. 1 Indonesia",
  desc: "Buat undangan digital elegan dalam hitungan menit dengan fitur buku tamu QR, amplop kado digital real-time, dan manajemen RSVP cerdas.",
  author: "Momen Invite Tech Team",
  teksNavbar: "🎉 Promo Spesial: Diskon 40% Tema Wedding Pilihan Bulan Ini!",
  keywords: ["undangan digital", "undangan pernikahan online", "amplop digital", "buku tamu qr", "rsvp online"],
};

export const MOCK_TRANSACTION_SETTINGS: TransactionSettings = {
  trxPrefixId: "INV",
  trxStartId: 1000,
  trxExpiredMinutes: 1440,
  trxDelayMinutes: 5,
};

export const MOCK_GATEWAY_SETTINGS: GatewaySettings = {
  waProvider: "Fonnte WhatsApp API",
  waDeviceName: "Gateway Notifikasi Server 1",
  waPhone: "081122334455",
  waApiUrl: "https://api.fonnte.com/send",
  waTokenMasked: "fonnte_prod_••••••••••••9a7e",
  waStatus: "aktif",
  emailSmtpHost: "smtp.resend.com",
  emailSmtpPort: 587,
  emailSenderAddress: "billing@momeninvite.com",
  emailSenderName: "Momen Invite Billing & System",
};

export const MOCK_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 501,
    actorAdminId: 1,
    actorName: "Adji Bhawanto (Superadmin)",
    actorRole: "superadmin",
    action: "WITHDRAWAL_APPROVED",
    entityName: "withdrawals",
    entityId: 1,
    ipAddress: "182.1.24.110",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/128.0",
    createdAt: "2026-09-08T07:10:00Z",
    details: "Mengesahkan penarikan dana Rp 5.000.000 ke rekening BCA host Rizky Firmansyah",
  },
  {
    id: 502,
    actorAdminId: 2,
    actorName: "Dina Operasional",
    actorRole: "admin",
    action: "ORDER_VERIFIED",
    entityName: "event_orders",
    entityId: 501,
    ipAddress: "103.20.14.5",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Safari/17.0",
    createdAt: "2026-09-08T06:45:00Z",
    details: "Memvalidasi pembayaran manual transfer order ORD-2026-08-001",
  },
  {
    id: 503,
    actorAdminId: 1,
    actorName: "Adji Bhawanto (Superadmin)",
    actorRole: "superadmin",
    action: "THEME_PUBLISHED",
    entityName: "event_product",
    entityId: 4,
    ipAddress: "182.1.24.110",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/128.0",
    createdAt: "2026-09-07T16:00:00Z",
    details: "Mempublikasikan tema baru 'Warm Memory Envelope Letter'",
  },
];
